### ISSUE TITLE
Haskell support is missing

### ISSUE THREAD

**Issue by lesguillemets** [haya14busa/niconicomment.vim#2]
Haskell is supported [by caw.vim](https://github.com/tyru/caw.vim/blob/bb24d3bb06bd1c193f2b7b161775989b833e0c8e/autoload/caw.vim#L368), but somehow it's missing from the [current niconicomment.vim code](https://github.com/haya14busa/niconicomment.vim/blob/master/autoload/niconicomment.vim#L233). I compared the codes and no other language seems to be missing.

**Comment by haya14busa** [comment]
It seems that I forgot to update caw.vim... Thanks!

**Comment by lesguillemets** [comment]
Thanks :+1:
